### ISSUE TITLE
When the path is not `/`, login fails

### ISSUE THREAD

**Issue by p-chan** [unix/next-password#1]
I wrote `initPasswordMiddleware` to `./pages/_middleware.ts`.

```ts
export default initPasswordMiddleware('/app', { password: '123' })
```

When I go to `/app` and enter `123`, the password is correct, but the login fails...

Is this the intended behavior?

**Comment by unix** [comment]
Thanks for the feedback, the issue has been fixed, now you can try the latest version(`next-password@0.1.4`).

**Comment by p-chan** [comment]
Thanks!
